# Generated by Django 5.1.3 on 2024-11-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='subtitle',
        ),
    ]
