# Generated by Django 5.1.4 on 2024-12-21 12:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('objectos', django.db.models.manager.Manager()),
            ],
        ),
    ]
